FROM node:18.5.0-slim
ENV REACT_APP_BACKEND_URL=http://localhost:8000/api
EXPOSE 4100
WORKDIR /app

COPY --chown=node:node . .

USER node

RUN npm install --force
CMD ["npm", "start"]

# Usa wget per controllare se la pagina web risponde
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 CMD wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1