name: "Unit & Integration Tests (Pytest)"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


    
jobs:
  test:
    name: Esecuzione Pytest
    runs-on: ubuntu-latest

    # I "Services" sono container temporanei che GitHub Actions avvia solo per la durata dei test.
    # Sono perfetti per testare le API (Integration Tests) senza dover usare server esterni.
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: capital_test_db
        ports:
          - 5432:5432
        # Aspettiamo che il DB sia pronto prima di far partire i test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

    steps:
    - name: Checkout del codice
      uses: actions/checkout@v4

    - name: Setup Python 3.12.0
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        # IL TRUCCO DELLA CACHE: GitHub salverà le librerie pip scaricate
        # velocizzando enormemente le build successive
        cache: 'pip' 

    - name: Installazione Dipendenze
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Installiamo pytest e i plugin essenziali per FastAPI
        pip install pytest pytest-cov httpx asgi_lifespan pytest-asyncio

    - name: Esecuzione dei Test con Pytest
      env:
        # Sovrascriviamo le variabili d'ambiente in modo che l'app punti 
        # ai database temporanei di test appena creati dai "services"
        DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/capital_test_db"
        APP_ENV: "test"
      run: |
        # Esegue i test e genera un report di "Coverage" (quanto codice è stato testato)
        pytest --cov=app --cov-report=term-missing