name: "SAST - SonarCloud"

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - uses: actions/checkout@v6 
        with:
          fetch-depth: 0 

      - name: SonarCloud Scan
        # nosemgrep: generic.secrets.security.detected-sonarqube-docs-api-key.detected-sonarqube-docs-api-key 
        uses: SonarSource/sonarqube-scan-action@v8 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Necessario per decorare le PR
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          # Passiamo esplicitamente l'organizzazione per evitare dubbi
          args: >
            -Dsonar.organization=lucazana14
            -Dsonar.projectKey=LucaZana14_php-goof

      - name: Carica i risultati su GitHub Security
        uses: github/codeql-action/upload-sarif@v4  
        if: always()
        with:
          sarif_file: sonarqube.sarif